// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewUser struct {
	Auth0ID   string `json:"auth0_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type User struct {
	UserID    string    `json:"user_id"`
	Auth0ID   string    `json:"auth0_id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
